services:
  swiss-grades:
    image: ghcr.io/arlind-dev/swiss-grades:latest
    container_name: swiss-grades
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - swiss-grades

networks:
  swiss-grades:
    name: swiss-grades
